export const USER_SUCCESSFUL_REGISTRATION = 'USER_SUCCESSFUL_REGISTRATION';
export const SET_CELLS = 'SET_CELLS';
export const SET_BOATS = 'SET_BOATS';
export const SET_CPU_BOATS = 'SET_CPU_BOATS';
export const CHANGE_GAME_STATUS = 'CHANGE_GAME_STATUS';
export const SET_CPU_CELLS = 'SET_CPU_CELLS';
