export const USER_SUCCESSFUL_REGISTRATION = 'USER_SUCCESSFUL_REGISTRATION';
export const SET_CELLS = 'SET_CELLS';
export const SET_BOAT = 'SET_BOAT';
export const CHANGE_GAME_STATUS = 'CHANGE_GAME_STATUS';
